# Generated by Django 5.1.1 on 2025-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile Phone'), ('monitor', 'Monitor'), ('പലചരക്ക്', 'പലചരക്ക്')], default='mobile', max_length=50),
        ),
    ]
