# Generated by Django 5.1.1 on 2025-12-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='amount',
        ),
    ]
