# Generated by Django 5.1.1 on 2025-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_orderitems_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile Phone'), ('monitor', 'Monitor')], default='mobile', max_length=50),
        ),
    ]
